# Generated by Django 2.0.7 on 2020-03-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0003_auto_20190427_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gunit',
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(blank=True, null=True, upload_to='df_goods/image/%Y/%m', verbose_name='商品图片'),
        ),
    ]
