# Generated by Django 2.0.7 on 2020-03-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0004_auto_20200324_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='gunit',
            field=models.CharField(default='500g', max_length=20, verbose_name='单位重量'),
        ),
    ]
