# Generated by Django 2.0.7 on 2020-03-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0005_goodsinfo_gunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gunit',
            field=models.CharField(max_length=20, verbose_name='单位重量'),
        ),
    ]
