# Generated by Django 2.0.7 on 2020-03-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0006_auto_20200324_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gunit',
            field=models.CharField(max_length=20, verbose_name='卖家昵称'),
        ),
    ]
