# Generated by Django 2.0.7 on 2020-03-30 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0007_auto_20200324_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('ctitle', models.CharField(max_length=20, unique=True, verbose_name='商品名称')),
                ('cpic', models.ImageField(blank=True, null=True, upload_to='df_goods/image/%Y/%m', verbose_name='商品图片')),
                ('cusername', models.CharField(max_length=20, verbose_name='买家昵称')),
                ('cuser_content', tinymce.models.HTMLField(max_length=200, verbose_name='用户评论')),
                ('date_publish', models.IntegerField(default=datetime.datetime.now, verbose_name='发表时间')),
                ('cgoodsname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='商品id')),
            ],
            options={
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
            },
        ),
    ]
