# Generated by Django 2.0.7 on 2020-04-01 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0008_goodscontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscontent',
            name='date_publish',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间'),
        ),
    ]
