# Generated by Django 2.0.7 on 2020-04-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0009_auto_20200401_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscontent',
            name='clogo',
            field=models.CharField(default=None, max_length=200, verbose_name='买家头像'),
        ),
    ]
