# Generated by Django 2.0.7 on 2020-04-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0010_goodscontent_clogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscontent',
            name='ctitle',
            field=models.CharField(max_length=20, verbose_name='商品名称'),
        ),
    ]
