# Generated by Django 2.0.7 on 2020-04-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0012_contentchart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentchart',
            old_name='cgoodsname',
            new_name='ccontent',
        ),
    ]
