# Generated by Django 2.0.7 on 2020-04-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0013_auto_20200404_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gprice',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格'),
        ),
    ]
