# Generated by Django 2.0.7 on 2020-05-12 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0014_auto_20200414_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscontent',
            name='cgoodsname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='外键商品'),
        ),
        migrations.AlterField(
            model_name='goodscontent',
            name='cpic',
            field=models.ImageField(blank=True, null=True, upload_to='df_goods/image/%Y/%m', verbose_name='上传图片'),
        ),
    ]
