# Generated by Django 2.0.7 on 2020-04-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0007_userinfo_ulogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ucheck_pass_or_fail',
            field=models.BooleanField(default=False, verbose_name='认证审批'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='urealname',
            field=models.CharField(default='', max_length=20, verbose_name='真实姓名'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uzhengjian_img',
            field=models.FileField(default='', upload_to='images/zhengjian_img', verbose_name='证件号码'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uzhengjian_tel',
            field=models.CharField(default='', max_length=20, verbose_name='证件号码'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='uzhengjian_type',
            field=models.CharField(default='', max_length=20, verbose_name='证件类型'),
        ),
    ]
