# Generated by Django 2.0.7 on 2020-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0008_auto_20200403_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uzhengjian_tel',
            field=models.CharField(default='', max_length=18, verbose_name='证件号码'),
        ),
    ]
