# Generated by Django 2.0.7 on 2020-04-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0012_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='ccheck',
            field=models.BooleanField(default=False, verbose_name='消息是否已读'),
        ),
    ]
