# Generated by Django 2.0.7 on 2020-05-12 16:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0013_information_ccheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uname_passOrfail',
            field=models.BooleanField(default=True, verbose_name='是否禁止登录'),
        ),
        migrations.AlterField(
            model_name='information',
            name='ccontent_chart',
            field=tinymce.models.HTMLField(max_length=200, verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ulogo',
            field=models.FileField(default='default.jpg', upload_to='images', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ushou',
            field=models.CharField(default='', max_length=20, verbose_name='收货名称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uzhengjian_img',
            field=models.FileField(default='', upload_to='images/zhengjian_img', verbose_name='证件图片'),
        ),
    ]
