# Generated by Django 2.0.7 on 2020-06-01 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0014_auto_20200512_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='tuihuoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=20, verbose_name='商品名称')),
                ('username', models.CharField(max_length=20, verbose_name='买家昵称')),
                ('username1', models.CharField(max_length=20, verbose_name='卖家昵称')),
                ('person_number', models.CharField(max_length=20, verbose_name='身份证号码')),
                ('order_number', models.CharField(max_length=20, verbose_name='订单号')),
                ('kuaidi', models.CharField(max_length=20, verbose_name='快递类型')),
                ('kuaidi_number', models.CharField(max_length=20, verbose_name='快递单号')),
                ('date_publish', models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '退款订单',
                'verbose_name_plural': '退款订单',
            },
        ),
    ]
