# Generated by Django 2.0.7 on 2020-06-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0016_tuihuoinfo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuihuoinfo',
            name='address',
            field=models.CharField(default=None, max_length=50, verbose_name='收获地址'),
        ),
        migrations.AlterField(
            model_name='tuihuoinfo',
            name='username',
            field=models.CharField(max_length=20, verbose_name='收件人姓名'),
        ),
        migrations.AlterField(
            model_name='tuihuoinfo',
            name='username1',
            field=models.CharField(max_length=20, verbose_name='寄件人姓名'),
        ),
    ]
