# Generated by Django 2.0.7 on 2020-06-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0017_auto_20200601_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuihuoinfo',
            name='address1',
            field=models.CharField(default=None, max_length=50, verbose_name='发获地址'),
        ),
    ]
