# Generated by Django 2.0.7 on 2020-06-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0018_tuihuoinfo_address1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuihuoinfo',
            name='address',
            field=models.CharField(default=None, max_length=50, verbose_name='收货地址'),
        ),
        migrations.AlterField(
            model_name='tuihuoinfo',
            name='address1',
            field=models.CharField(default=None, max_length=50, verbose_name='发货地址'),
        ),
    ]
