# Generated by Django 2.0.7 on 2020-06-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0019_auto_20200601_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuihuoinfo',
            name='passOrdefault',
            field=models.BooleanField(default=False, verbose_name='同意退款'),
        ),
    ]
