# Generated by Django 2.0.7 on 2020-04-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0002_auto_20181218_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailinfo',
            name='username',
            field=models.CharField(default=None, max_length=20, verbose_name='买家昵称'),
        ),
    ]
