# Generated by Django 2.0.7 on 2020-05-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0005_orderdetailinfo_datatime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetailinfo',
            options={'verbose_name': '付款订单', 'verbose_name_plural': '付款订单'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '未付款订单', 'verbose_name_plural': '未付款订单'},
        ),
    ]
